### ISSUE TITLE
Podatki

### ISSUE THREAD

**Issue by AMihevc** [AMihevc/HackhatONFree#4]
- [ ] iskanje podatkov
- [ ] čiščenje podatkov 
- [ ] pretvarjanje podatkov 
- [ ] feature engenirenig
- [ ] train, test, validation split

**Comment by timopetric** [comment]
- [x] Preverit kako dobit arso history podatke

**Comment by timopetric** [comment]
dodatni primeri zbirk:
https://hackathon.si/izziv-1/

**Comment by timopetric** [comment]
- [ ] https://podatki.gov.si/dataset/podatki-o-meritvah-padavin-in-opazovanjih-vremena-na-padavinskih-postajah
- [ ] https://podatki.gov.si/dataset/opozorilna-karta-poplav
- [ ] https://podatki.gov.si/dataset/integralna-karta-razredov-poplavne-nevarnosti-ikrpn
- [ ] https://podatki.gov.si/dataset/hidroloske-meritve-na-povrsinskih-vodah
